name: VToaster
description: Make some toasts!
version: 1.0.0-PoC
author: m.vezdehod

api: [4.0.0]
main: vezdehod\toaster\VToasterMain

commands:
  toast:
    description: send toast
    permission: vtoaster.toast
    usage: "/toast <target> <toast> <...header> -m <...message> [-s: silent?] [-n: now?]"
permissions:
  vtoaster.toast:
    description: use /toast
    default: op