toasts:
  default:
    icon: textures/gui/newgui/ChainSquare.png
    sound: ClickSound
  error:
    # ./ equals plugin_data/VToaster/
    icon: ./error.png
    sound: AnvilFallSound
  warning:
    icon: https://files.softicons.com/download/internet-icons/3d-ii-icons-by-la-glanz-studio/png/256/warning.png
    sound: BlazeShootSound